### PR TITLE
ros_kortex_vision requires the robot description to contain the camera module frames

### PR DESCRIPTION
**Pull request by RaduCorcodel**
Added camera frames to gen3-7dof description so the vision module can work correctly.
Frames added:
- camera_link
- camera_depth_frame
- camera_color_frame

### CODE REVIEW

**Comment by alexvannobel** [comment]
Hi @RaduCorcodel ,

This looks good to me.
I'll test that real quick when I have access to hardware and I'll merge this.

Thanks a lot for the contribution!
Best regards,
Alex

**Comment by RaduCorcodel** [comment]
Any luck testing and merging this pull request?

**Comment by alexvannobel** [comment]
Hi @RaduCorcodel ,

No since we work remotely and I can only access the arms by VPN for now, but I merged it and if anything comes up I'll fix it there and then, but as I said it looks alright to me.

Thanks again,
Best,
Alex

**Comment by juntuck** [comment]
Hi all,

Thanks very much for placing the end_effector_link <-> camera_link transform inside the Gen3 URDF, it was much needed from our side! :)

Apart from that, this commit also added camera_link <-> camera_depth frame and camera_link <-> camera_color_frame transforms. These seem to me, at first glance, redundant with the static transform publishers spawned by the kinova_vision package [here](https://github.com/Kinovarobotics/ros_kortex_vision/blob/master/launch/kinova_vision.launch#L91).

There seems to be no issues launching kortex_driver.launch and kinova_vision.launch. However, I'm not sure if it is a best ROS practice to have both a static transform publisher broadcasting a static transform that already exists via URDF. What do you think?

**Pull request merged**
