### PR TITLE
[conan] Use the closes build type that is compatible

### PR DESCRIPTION
**Pull request by gergondet**
See #279

### CODE REVIEW

**Comment by felixmaisonneuve** [comment]
Following your suggestion in #279, could you add something like "Note : Only `Release` and `Debug` are supported for the `CMAKE_BUILD_TYPE` argument" in the main readme file after the `catkin_make` instruction?

**Comment by gergondet** [comment]
Hi @felixmaisonneuve 

Do you mean instead of this PR or in addition to this PR?

Thanks

**Comment by felixmaisonneuve** [comment]
@gergondet in addition this PR

**Comment by gergondet** [comment]
@felixmaisonneuve thanks, I have added the note in [`24da986` (#280)](https://github.com/Kinovarobotics/ros_kortex/pull/280/commits/24da986d6a6babd817e7ac264fe9b13ad346ca96)

**Comment by felixmaisonneuve** [comment]
This looks good, thank you for your work

I am sory I did not merge this earlier

Regards,
Felix

**Pull request merged**
